### ISSUE TITLE
update all instances of RSpec code example syntax

### ISSUE THREAD

**Issue by MarchandMD** [MrPowers/tic_tac_toe#7]
current tutorial RSpec code example syntax: 
```ruby
# spec/cell_spec.rb
module TicTacToe
  describe Cell do

# other awesome code here
 
  end
end
```
suggested new tutorial RSpec code example syntax: 
```ruby
# spec/cell_spec.rb
module TicTacToe
  RSpec.describe Cell do # it's a small thing, but it's honest work lol

# other awesome code here
 
  end
end
```

**Comment by MrPowers** [comment]
@MarchandMD - thanks for opening this issue.  Please feel free to submit a pull request.  I haven't worked with Ruby in a while, but would be happy to get this project updated!
